version: '3'

services:
  db:
    image: postgres
    restart: on-failure
    ports:
      - "5432:5432"
    volumes:
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      TZ: America/Sao_Paulo
      POSTGRES_DB: account
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  mosquitto:
    image: eclipse-mosquitto:1.6.14
    hostname: mosquitto
    container_name: mosquitto
    expose:
      - "1883"
      - "9001"
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - .:/config/mosquitto.conf

  api:
    build: .
    restart: on-failure
    command: python src/run.py
    volumes:
      - .:/api-challenge
    ports:
      - "8000:8000"
    env_file: config/api.env
    depends_on:
      - db
      - mosquitto
